-- create a table called users	--Comment
CREATE	--Keyword
	TABLE	--Keyword
	users	--Identifier
	(	--Separator
	id	--Identifier
	SERIAL	--DataType
	PRIMARY	--Keyword
	KEY	--Keyword
	,	--Delimiter
	name	--Identifier
	varchar	--Identifier
	(	--Separator
	32	--Identifier
	)	--Separator
	NOT	--Keyword
	NULL	--Keyword
	,	--Delimiter
	_active	--Identifier
	BOOLEAN	--DataType
	DEFAULT	--Keyword
	TRUE	--Keyword
	NOT	--Keyword
	NULL	--Keyword
	,	--Delimiter
	last_initial	--Identifier
	char	--Identifier
	(	--Separator
	1	--Identifier
	)	--Separator
	,	--Delimiter
	UNIQUE	--Keyword
	(	--Separator
	name	--Identifier
	)	--Separator
	)	--Separator
	;	--End
-- insert some people into the table	--Comment
INSERT	--Keyword
	INTO	--Keyword
	users	--Identifier
	(	--Separator
	name	--Identifier
	,	--Delimiter
	last_initial	--Identifier
	)	--Separator
	VALUES	--Keyword
	(	--Separator
	'Isaac''s'	--Identifier
	,	--Delimiter
	'L'	--Identifier
	)	--Separator
	,	--Delimiter
	(	--Separator
	'Zachary'	--Identifier
	,	--Delimiter
	'L'	--Identifier
	)	--Separator
	,	--Delimiter
	(	--Separator
	'Jordan'	--Identifier
	,	--Delimiter
	'Y'	--Identifier
	)	--Separator
	,	--Delimiter
	(	--Separator
	'\tRemington'	--Identifier
	,	--Delimiter
	'D'	--Identifier
	)	--Separator
	;	--End
-- select users based on criteria	--Comment
SELECT	--Keyword
	name	--Identifier
	,	--Delimiter
	_active	--Identifier
	FROM	--Keyword
	users	--Identifier
	WHERE	--Keyword
	name	--Identifier
	LIKE	--Keyword
	'%a%'	--Identifier
	AND	--Keyword
	last_initial	--Identifier
	=	--ComparisonOperator
	'l'or	--Identifier
	age	--Identifier
	>=	--ComparisonOperator
	10	--Identifier
	;	--End
/*
 that is all!
*/	--Comment
SELECT	--Keyword
	*	--ArithmeticOperator
	FROM	--Keyword
	users	--Identifier
	;	--End
-- finally, all users	--Comment
