-- create a table called users	--Comment
	--IdentifierCREATE	--Keyword
	TABLE	--Keyword
	users	--Identifier
	(	--Identifier
	id	--Identifier
	SERIAL	--DataType
	PRIMARY	--Keyword
	KEY	--Keyword
	,	--Identifier
	name	--Identifier
	varchar	--Identifier
	(	--Identifier
	32	--Identifier
	)	--Identifier
	NOT	--Keyword
	NULL	--Keyword
	,	--Identifier
	_active	--Identifier
	BOOLEAN	--DataType
	DEFAULT	--Keyword
	TRUE	--Keyword
	NOT	--Keyword
	NULL	--Keyword
	,	--Identifier
	last_initial	--Identifier
	char	--Identifier
	(	--Identifier
	1	--Identifier
	)	--Identifier
	,	--Identifier
	UNIQUE	--Keyword
	(	--Identifier
	name	--Identifier
	)	--Identifier
	)	--Identifier
	;	--End
	--Identifier-- insert some people into the table	--Comment
	--IdentifierINSERT	--Keyword
	INTO	--Keyword
	users	--Identifier
	(	--Identifier
	name	--Identifier
	,	--Identifier
	last_initial	--Identifier
	)	--Identifier
	VALUES	--Keyword
	(	--Identifier
	'Isaac''s'	--Identifier
	,	--Identifier
	'L'	--Identifier
	)	--Identifier
	,	--Identifier
	(	--Identifier
	'Zachary'	--Identifier
	,	--Identifier
	'L'	--Identifier
	)	--Identifier
	,	--Identifier
	(	--Identifier
	'Jordan'	--Identifier
	,	--Identifier
	'Y'	--Identifier
	)	--Identifier
	,	--Identifier
	(	--Identifier
	'\tRemington'	--Identifier
	,	--Identifier
	'D'	--Identifier
	)	--Identifier
	;	--End
	--Identifier-- select users based on criteria	--Comment
	--IdentifierSELECT	--Keyword
	name	--Identifier
	,	--Identifier
	_active	--Identifier
	FROM	--Keyword
	users	--Identifier
	WHERE	--Keyword
	name	--Identifier
	LIKE	--Keyword
	'%a%'	--Identifier
	AND	--Keyword
	last_initial	--Identifier
	=	--ComparisonOperator
	'l'or	--Identifier
	age	--Identifier
	>=	--ComparisonOperator
	10	--Identifier
	;	--End
	--IdentifierSELECT	--Keyword
	*	--ArithmeticOperator
	FROM	--Keyword
	users	--Identifier
	;	--End
	--Identifier-- finally, all users	--Comment
